### ISSUE TITLE
show source under article names

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/magnetics#320]
Hey @emdecr 

Melissa would like to site the publication source under all articles (that appear on product pages and in resources).

Something like this!

![screen shot 2016-04-27 at 4 40 09 pm](https://cloud.githubusercontent.com/assets/10924897/14867502/cd6dcc36-0c96-11e6-93ca-5ce047fa81f5.png)

**Comment by emdecr** [comment]
There's now an extra field to input a publication source.
http://hypelabs.ca/dev/magnetics/resources/
