### ISSUE TITLE
Is it possible to replace the main image banner with a video?  

### ISSUE THREAD

**Issue by lionelmann** [hypenotic/magnetics#364]
## Details
**Created by:** Jennifer Phelan

**Feedback from:** jen@hypenotic.com

**Assigned to:** Lionel Mann

**Priority:**  normal

[Open Note](https://app.pageproofer.com/to/note/183647)

## Note
> Is it possible to replace the main image banner with a video?  
This is the embed link: &amp;lt;iframe src=&amp;quot;https://player.vimeo.com/video/459125731&amp;quot; width=&amp;quot;640&amp;quot; height=&amp;quot;360&amp;quot; frameborder=&amp;quot;0&amp;quot; allow=&amp;quot;autoplay; fullscreen&amp;quot; allowfullscreen&amp;gt;&amp;lt;/iframe&amp;gt;

## Browser Information
**Window Size:** 1344 x 634
**Screen Size:** 1680 x 1050
**Device:** Macintosh
**Browser:** Chrome version: 85.0.4183.102
**Platform:** OS X version: 10_15_6

**Comment by lionelmann** [comment]
This is the embed link: &lt;iframe src=&quot;https://player.vimeo.com/video/459125731&quot; width=&quot;640&quot; height=&quot;360&quot; frameborder=&quot;0&quot; allow=&quot;autoplay; fullscreen&quot; allowfullscreen&gt;&lt;/iframe&gt;

**Comment by jenphelan** [comment]
We discussed chrome no longer supports autolooping videos... :(
