### ISSUE TITLE
Change contact email

### ISSUE THREAD

**Issue by rstender** [hypenotic/magnetics#367]
On [products page](https://hypelabs.dev/magnetics/products/)

Please change contact email under ROV Integration to gina.lopez@marinemagnetics.com instead of mm@ (melissa)

![mm_contact_email](https://user-images.githubusercontent.com/1899319/98020493-143f5f80-1dd1-11eb-8abd-856d4f853d68.png)

**Comment by jenphelan** [comment]
done
