### ISSUE TITLE
can't find timeline in backend for AUV Towed Integration page (dev site)

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/magnetics#369]
Hi Lionel,
I need to edit the timeline on this page.
Can't find it the timeline in the backend.
It's on the live site though (backend).

**Comment by jenphelan** [comment]
In the meantime, I'm trying to get a text change up on the live site version of this page (the timeline is visible on the live backend) but timeline updates to the page don't show on the front end... please help!

**Comment by jenphelan** [comment]
Noticed the backend timeline missing on the dev site for the seaspy 2 page, assume it's missing on all the pages?

**Comment by lionelmann** [comment]
Confirmed the code is correct. The issue most likely is an unclosed <table> tag in the WP admin content itself.
